### ISSUE TITLE
Aggégation de contenu live sur le site 

### ISSUE THREAD

**Issue by benborges** [nuitdeboutbe/nuitdeboutbe.github.io#2]
voici un pad qui permet d'intégrer l'outil "rebelmouse" qui fait office d'outil de veille sur twitter (peut aussi faire facebook, instagram, youtube, etc...) https://titanpad.com/nuitdeboutcode

exemple sur mon site : https://1-m.cc/pages/nuitdebout

l'activité à bruxelles : https://www.rebelmouse.com/nuitdebout/NuitDeboutBXL/

**Comment by nuitdeboutbe** [comment]
:+1:
